Buzzvil/hover

hover/src/main/java/io/mattcarroll/hover/HoverViewStateClosed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateExpanded.java

https://github.com/Buzzvil/hover/pull/1 이 PR에서 NPE fix 만 분리했습니다.
- If each of the HoverViewState's callback is fired after it has lost control (by `changeState()`), the NPE can occur because mHoverView has been set to null.
- Added checking whether the HoverViewState instance still has control (by checking `mHasControl`) in each of the callbacks.
기존 마스터 상태에서 샘플을 빌드해서 쓸때, State( = HoverViewStateClosed, HoverViewStateCollapsed, HoverViewStateExpanded 중 하나) 들을 빠르게 변경하면 (ex. Expanded 상태로 변하는 중에 백버튼 눌러서 Collapsed 로 만들기) 바로 NPE 가 발생하는 등 불안정한 상태였습니다.
원인을 분석해 보니 State 가 다른 State 로 전환될 때 이전 State 에서의 HoverView 에 대한 레퍼런스를 null 처리로 끊어버리는데, 몇가지 콜백들이 다른 State 로 전환된 이후에 발생할 수 있어서 모든 콜백에 대해 현재 컨트롤을 가지고 있는지 (기존에 정의되어 있던 변수, mHasControl) 를 확인하는 식으로 NPE 를 방지했습니다.

Fix NPE resulting from HoverViewState's callback after it already lost control

---

hover/src/main/java/io/mattcarroll/hover/Dragger.java
hover/src/main/java/io/mattcarroll/hover/HoverView.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStatePreviewed.java
hover/src/main/java/io/mattcarroll/hover/Screen.java
hover/src/main/java/io/mattcarroll/hover/view/InViewDragger.java
hover/src/main/java/io/mattcarroll/hover/window/InWindowDragger.java

- before : Dragger 는 `Point dragStartCenterPosition` 을 입력받으면 그 주변으로 고정된 크기의(75dp) touchDiameter 만큼의 Drag area 를 만든다.
- after : Drag area 를 Rect 로 만들어서 Dragger 에 넘긴다. Rect 를 만드는 방식은 HoverViewStateCollapsed, HoverViewStatePreviewed 마다 각각 다르다.

[BZZRWRDD-165] MessageView 영역도 drag, tab 가능하게 만들기

---

hover/src/main/java/io/mattcarroll/hover/BaseHoverViewState.java
hover/src/main/java/io/mattcarroll/hover/HoverView.java
hover/src/main/java/io/mattcarroll/hover/HoverViewState.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateAnchored.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateClosed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateExpanded.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStatePreviewed.java
hover/src/main/java/io/mattcarroll/hover/Screen.java

- HoverViewState 변경 로직 리팩토링
- State 가 변경되면 HoverView -> HoverViewState -> HoverView 이런 식으로 순환하면서 변경 로직을 처리해줘서 알아보기가 힘들었음
- 각 HoverViewState 는 takeControl, giveUpControl 로직 구현에 신경을 쓰고, State 간의 transition 은 HoverView 에서 전담한다.
```java
// In HoverView
void setState(@NonNull HoverViewState newState, Runnable onStateChanged) {
if (mState != newState) {
if (mState != null) {
mState.giveUpControl(newState);
}
mState = newState;
mState.takeControl(this, onStateChanged);
}
}
```
- HoverViewState interface 에서 state 의 역할에 맞지 않는 메소드는 제거함
- OnStateChangeListener 에서 아직은 쓰일 일이 없을 것 같기도 하고, 케이스의 구분이 애매해서 ~ing 콜백은 제거하고 ~ed 콜백만 남김
- OnInteractionListener 추가. FloatingTab 과 유저의 인터렉션을 통해 발생하는 이벤트에 대한 콜백. 이번에 액티비티를 띄울 때에도 필요하고, 이후 드래그 중일때 메세지를 보여주는 로직에서도 쓰일 수 있음
- HoverViewStateAnchored 추가. FloatingTab 이 지정된 …

[BZZRWRDD-252] Added 'Anchored' State for not using ContentDisplay, refactor callbacks

---

hover/src/main/java/io/mattcarroll/hover/BaseTouchController.java
hover/src/main/java/io/mattcarroll/hover/Dragger.java
hover/src/main/java/io/mattcarroll/hover/HoverView.java
hover/src/main/java/io/mattcarroll/hover/HoverViewState.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateAnchored.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateClosed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateExpanded.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStatePreviewed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateType.java
hover/src/main/java/io/mattcarroll/hover/view/InViewDragger.java
hover/src/main/java/io/mattcarroll/hover/window/InWindowDragger.java
hover/src/main/res/values/dimens.xml

문제 상황
- HoverView 를 윈도우에 붙일 때 처음부터 스크린의 전체 영역으로 붙이기 때문에 WindowManager 에서 특정 뷰만 집어내어 touchable 하게 바꾸기에는 어려운 구조
- 기존의 Dragger 는 FloatingTab 의 위치에 Drag 가능한 커버 뷰를 새로 만들어서 붙이는데, Dragger 에서 DragStart 뿐만 아니라 Tap, Press 등의 성격이 다른 이벤트도 같이 처리하고 있다.
- 지금 필요한 기능은 Dragger 에서 '커버 뷰가 실제로 Draggable 한' 피쳐를 제거하고, Tap, Press 이벤트만을 받는 것이다.
변경 내용
- Dragger 에서 위와 같이 기본 기능을 분리해 내기 위해 먼저 InWindowDragger 와 InViewDragger 에서 변경이 필요한 부분만 인터페이스로 분리하고, 나머지 공통 기능은 Dragger 에서 직접 구현하도록 리팩토링 (Dragger 를 interface 에서 abstract class 로 변경)
- Dragger 에서 Touch 관련된 기능만 분리해서 그걸 `BaseTouchController` 로 이름짓고 Dragger 가 이를 상속받아서 본래의 dragger 기능으로 확장시키도록 함. 
- 최종적인 클래스 간의 의존 관계는 다음과 같다
- BaseTouchController
- <- Dragger
- <- InWindowDragger
- <- InViewDragger
- HoverViewStateAnchored 에서 takeControl 이 불릴 때에는 Collapsed 와 다르게 …

[BZZRWRDD-262] Anchored 일때 Drag없이 터치만 가능하도록 Dragger의 일부를 TouchController 로 분리하고 Window, View 공통 요소 분리

---

hover/src/main/java/io/mattcarroll/hover/FloatingTab.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateAnchored.java
hover/src/main/res/values/dimens.xml

- Anchored 아이콘 변경 : PopConfig 에서 전달하는 아이콘 Drawable 에 android:state_selected="true" item 을 따로 정의해서 구현한다. 라이브러리에서는 Anchored 일때 setSelected() 만 호출해 준다.
- Anchored 사이즈 변경 : FloatingTab 에 shrink, expand 메소드 구현

[BZZRWRDD-262] Floating Tab 아이콘, 사이즈 변경시키기 (for AnchoredState)

---

hover/src/main/java/io/mattcarroll/hover/TabMessageView.java

이 앞의 PR과 동일한데, MessageView 를 빼먹어서 다시 올려요. @josh-yun 리뷰는 시간 나실 때 확인만 부탁드립니다. 먼저 머지할게요~

[BZZRWRDD-262] Disable 'clipping' to use shadow around child view - in TabMessageView

---

hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStatePreviewed.java
hover/src/main/java/io/mattcarroll/hover/Screen.java
hover/src/main/java/io/mattcarroll/hover/TabMessageView.java

- 현상
- 기존에는 TabMessageView가 한번 뜬 이후에는 Service 가 종료되기 전까지 그 뷰를 다시 보여줄 일이 없었는데 PopControlService 를 Foreground 로 변경하면서 한 서비스 생명주기 내에서 TabMessageView 를 재사용하게 되었습니다. 분명히 업데이트가 필요할 때 새로운 Menu, Section 내에 새로운 MessageView 를 생성해서 넘겼음에도 불구하고 UI가 변경되지 않아서 디버깅 해보았더니 MessageView 가 한번 고정된 UI 에서 더이상 변화할 수 없는 상태였습니다.
- 해결
- Preview State 로 변할 때마다 항상 최신의 MessageView 를 가져와서 보여줄 수 있도록 변경

Preview 모드에서 MessageView UI가 업데이트 되지 않던 현상 수정

---

hover/src/main/java/io/mattcarroll/hover/FloatingTab.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java

다행스럽게도 View 에서 Configuration Change 를 감지하는 메소드가 있었네요! @josh-yun 
https://developer.android.com/reference/android/view/View.html#onConfigurationChanged(android.content.res.Configuration)
HoverViewStateCollapsed 에서 구현된 View.OnLayoutChangeListener 는 Orientation Change 를 위한 것이니 이것으로 대체하고 제거했습니다

[BZZRWRDD-280] Docked 여부와 상관 없이 Orientation Changed 가 불리면 FloatingTab 을 정상 위치로 이동

---

hover/src/main/java/io/mattcarroll/hover/BaseTouchController.java
hover/src/main/java/io/mattcarroll/hover/Dragger.java
hover/src/main/java/io/mattcarroll/hover/HoverView.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/view/InViewDragger.java
hover/src/main/java/io/mattcarroll/hover/window/InWindowDragger.java
hover/src/main/java/io/mattcarroll/hover/window/WindowViewController.java

* Drag 직 후 바로 tap을 할 경우 NPE가 발생하는 이슈도 같이 수정했습니다!

[BZZRWRDD-284] Floating Button을 아래로 드래그하면 버튼이 안보이는 현상 수정

---

hover/src/main/java/io/mattcarroll/hover/HoverView.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateHidden.java

HiddenState로 state가 전환될 때, onStateChanged listener를 호출 한 후 바로 view의 visibility를 바꿀 경우 버튼이 깜빡거리는듯한 느낌을 주게됩니다. 그래서 handler를 사용해 약간의 딜레이를 넣었습니다.

Hidden State으로 전환될 때 Animation 추가

---

hover/src/main/java/io/mattcarroll/hover/HoverView.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java

일정 시간이 지났을 때 아이콘이 사라졌으면 좋겠다는 의견이 있어서 옵션으로 켰다 껐다 할 수 있도록 구현을 했습니다.

Collapsed state일 때 일정 시간이 지나면 반투명해지거나 아이콘이 사라질 수 있도록 설정할 수 있게 변경

---

hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStatePreviewed.java
hover/src/main/java/io/mattcarroll/hover/TabMessageView.java

Preview 드래그 기능의 구현이 오래 걸릴 것 같으므로, 일단 현재 구현된 것들은 적용하고 가는 것이 좋을 것 같아 PR을 올립니다.
* Pop을 드래그하면 Preview가 사라지는 기능을 구현하였습니다.
* 위치 정보에 대해서 불필요하게 뜨는 로그를 제거하였습니다.
* HoverViewStatePreviewed.onPickedByUser()에서 messageView의 disappear를 애니메이션과 함께 실행하게 하고, mCollapseOnDocked를 true로 설정합니다.
* HoverViewStatePreviewed.onDocked()에서 mCollapseOnDocked가 true이면 collapse 상태로 변경합니다. 이 때, 애니메이션이 없도록 하기 위해서 mTurnOffNextCollapseAnimation를 true로 설정합니다.
* HoverViewStatePreviewed.onDroppedByUser()에서 변수들을 초기화합니다. 지금은 mCollapseOnDocked 필드 하나만 있습니다. Service는 HoverView를 매 번 새로 생성하지 않고, 한 번 생성한 후 재사용하기 때문에 Drop되는 시점에서 변수를 초기화 해주어야 합니다.
* TabMessageView의 appear()와 disappear()에서 애니메이션을 적용할 때, 현재 Visibility를 체크하여 애니메이션을 적용할지 여부를 결정합니다.
* (위치, 옆면)가 기존과 동일하고 getWidth()가 0이 아닌 경우에는 위치 정보에 대한 로그를 띄우지 않습니다. 기존에는 같은 위치 정보임에도 계속해서 여러개의 …

[BZZRWRDD-322] Pop의 드래그가 시작되면 Preview가 닫히는 기능 구현

---

hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java

낮은 버전의 안드로이드(21 이전)에서 ViewGroup에 setAlpha를 할 때 적용이 안되는 이슈가 있어서 floatingTabView의 Alpha 값을 변경하도록 코드를 수정했습니다.

낮은 버전의 안드로이드에서 alpha값이 적용되지 않는 버그 수정

---

hover/src/main/java/io/mattcarroll/hover/BaseTouchController.java
hover/src/main/java/io/mattcarroll/hover/ContentDisplay.java
hover/src/main/java/io/mattcarroll/hover/Dragger.java
hover/src/main/java/io/mattcarroll/hover/FloatingTab.java
hover/src/main/java/io/mattcarroll/hover/HoverFrameLayout.java
hover/src/main/java/io/mattcarroll/hover/HoverMenu.java
hover/src/main/java/io/mattcarroll/hover/HoverView.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStatePreviewed.java
hover/src/main/java/io/mattcarroll/hover/Screen.java
hover/src/main/java/io/mattcarroll/hover/TabChain.java
hover/src/main/java/io/mattcarroll/hover/TabMessageView.java

변경 사항이 많아서 한 번 코드 리뷰를 하고 가는 것이 좋을 것 같습니다.
HS QA버전 나가고 나면 머지하면 어떨까 싶습니다.
Preview를 옆으로 드래그해서 없앨 수 있습니다.
* Pop과 Preview의 드래그 이벤트를 서로 다른 것으로 구분하여 동작합니다.
* 이를 위해서 `Dragger.mDragTouchListener`와 `BaseTouchController.mDragTouchListener`를 각각 `TouchDetector`, `DragDetector` 클래스로 만들고 View에 따라서 적절하게 생성하는 것으로 변경하였습니다.
* Pop의 드래그 이벤트는 `HoverViewStateCollapsed.FloatingTabDragListener`에서 구현하고 있습니다.
* Preview의 드래그 이벤트는 `HoverViewStatePreviewed.DefaultMessageViewDragListener`에서 구현하고 있습니다.
* 터치 영역의 위치 조정을 onLayoutChangeListener에서 하던 것을 커스텀 콜백인 onPositionChangeListener에서 하도록 변경하였습니다. 이는 setX(), setY()등의 애니메이션을 사용하는 경우 onLayoutChangeListener()가 불리지 않기 때문입니다.
* Menu가 업데이트되면 TabView를 업데이트하도록 하였습니다. 기존 구현에서는 Pop이 보이는 상태에서 다시 SHOW_POP 버튼을 누른 경우, 화면에는 이전에 생성된 FAB가 보이지만 코드로 접근하는 FAB 객체는 새로 생성된 객체인 문제가 있었습니다.
* …

[BZZRWRDD-322] Pop과 Preview의 터치/드래그 이벤트 등을 얻을 수 있도록 인터페이스 구현

---

hover/src/main/java/io/mattcarroll/hover/HoverView.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/TabMessageView.java

Pop 관련 data를 hover library에서 보내는 것은 아닌 것 같아 인터페이스를 추가하였습니다.
- TabMessageView가 가지고있는 messageView를 가져올 수 있게 바꾸어 현재 보여지고있는 view가 ad인지 content인지 구분 할 수 있게 되었습니다.
- Pop의 idle모드를 boolean 값으로 visibility만 바꿀 수 있는 상태였는데요. 이 부분을 View의 상태를 직접 변경할 수 있도록 인터페이스를 만들어 외부에서 동작을 정의할 수 있도록 변경하였습니다.

Data Tracking에 필요한 인터페이스 구현

---

hover/src/main/java/io/mattcarroll/hover/HoverViewStateClosed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java

OnExitListener가 close state으로 변경되면 무조건 불리고 있습니다.
유저가 강제로 끌 경우에만 호출이 되도록 변경을 하였습니다.
close state으로 가는 경우는 stateChangedListener의  onClosed()를 통해 할 수 있습니다.

OnExitListener가 의미대로 동작하지 않는 문제 수정

---

hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/window/WindowViewController.java

다음과 같은 상황에서 crash가 발생하는 이슈를 수정하였습니다.
- 시간이 지나서 Pop이 자동으로 close state로 전환이 되기 직전에 터치를 시작 할 경우, long press 이벤트가 HoverView가 사라지고나서 불리게되어 NPE가 발생
- Touch/Drag 이벤트가 불릴때 현재 state의 hasControl 여부를 확인하여 동작을 수행하도록 변경
- 사용자가 overlay permission을 revoke 할 경우, window에 view를 add하거나 layout을 업데이트하면 Exception이 발생
- addView -> WindowManager.BadTokenException permission denied 발생
- updateLayout -> IllegalArgumentException -> View가 window에 붙어있지 않아 업데이트 불가 에러

Hover crash fix

---

hover/src/main/java/io/mattcarroll/hover/ExitView.java
hover/src/main/java/io/mattcarroll/hover/FloatingTab.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/SideDock.java
hover/src/main/res/drawable/ic_exit.xml
hover/src/main/res/layout/view_hover_menu_exit.xml

- ExitView 에 애니메이션 추가
나타날때, 사라질때, 종료영역 진입/이탈 시
- HoverViewStateCollapsed. onDroppedByUser 에 gesture 추가
좌/우 스와이프: Pop 위치 변경
아래로 스와이프: Pop 종료
TargetY 포지션은 x 가 0 or screen.width 일 때, 스와이프 한 방향과 만나는 지점으로 계산했습니다.

[CD-51] Close pop with gesture, add animation

---

hover/src/main/java/io/mattcarroll/hover/FloatingTab.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStatePreviewed.java

팝을 Throw 해서 종료 애니메이션 중에, showPop을 할 경우 팝아이콘이 사라지는 문제를 수정
- Disappear 애니메이션 중인데, 이를 감지하지 못하고, 그냥 show 상태로 인식한 것이 문제
- show 상태에서도 명시적으로 Appear (without animation)를 수행하도록 변경
- disappearing 애니메이션이 실행 중이면 중단하는 코드도 추가

[CD-91] Fix disappearing pop icon

---

hover/src/main/java/io/mattcarroll/hover/ExitView.java
hover/src/main/java/io/mattcarroll/hover/FloatingTab.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStateCollapsed.java
hover/src/main/java/io/mattcarroll/hover/HoverViewStatePreviewed.java

- 일부 단말에서 소수점 연산으로 인해 throwing close 되지 않는 경우가 있어서 isInExitZone 내에 safe margin 1 px 추가
- throwing 속도를 좀 더 잘 측정하기 위해 GestureBlackBox 추가
최대 100개의 이동경로를 수집하고, 
100ms 내에 이동한 방향, 속도를 측정합니다

[CD-82] Fix pop throw close
